version: 1
services:
  - type: web
    name: MyTelegramBot
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install python3-venv python3-pip -y && \
      python3 -m venv myenv && \
      source myenv/bin/activate && \
      pip install -r requirements.txt
    startCommand: |
      source myenv/bin/activate && \
      python3 m.py
    
